testscript: import timeout behavior from stdlib
rogpeppe/go-internal pull request #171
Opened 2022-07-28 12:31 UTC by FiloSottile

This uses the `-test.timeout` flag (or the `Params.Deadline` field) to send first `SIGQUIT` (to get a stack trace) and then `SIGKILL` to a stuck command. It's mostly imported from the current stdlib code, with tweaks to work around the lack of Deadline and Cleanup method access.

2022-07-28 14:14 UTC, mvdan commented
Did you somehow write this PR on top of an older master? GitHub reports conflicts :)

2022-07-28 14:35 UTC, FiloSottile commented
Ah yep, I did, I've been using this for a bit in my fork. I'll rebase.

2022-08-22 08:39 UTC, mvdan requested changes
Requesting changes as a reminder that this needs a rebase.

2022-12-27 00:28 UTC, FiloSottile commented
Conflict resolved! :)

2023-01-13 16:43 UTC, mvdan commented
There are conflicts again, my apologies. We recently merged a regression in the -continue flag, and I forgot that this was in flight already. If you can fix them again, which should hopefully not be too hard, I'll make sure to review quickly.

2023-01-13 16:50 UTC, FiloSottile commented
Done!

2023-01-13 21:18 UTC, mvdan approved these changes
Thanks! For some context, this started appearing upstream in https://go-review.googlesource.com/c/go/+/233526.

2023-01-13 21:18 UTC, merged

2024-02-10 09:59 UTC, myitcv commented
@FiloSottile - out of interest, why did this line get added as part of this change?

https://github.com/rogpeppe/go-internal/blame/2c88e7f58ae1ca6f811b818d0d985b4622556532/testscript/testscript.go#L443

It appears unrelated to the main purpose of the PR, but would like to check whether I'm missing something in that analysis.